# compose all the microservices containers
version: '3.7' # specify docker-compose version
services:
  router:
    container_name: router
    restart: always
    build:
      context: ./router
      dockerfile: Dockerfile    
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - auth
      - production
      - promptify
      - prompts

  auth:
    container_name: auth
    restart: always
    build:
      context: ./auth
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
  
  production:
    container_name: production
    restart: always
    build:
      context: ./production
      dockerfile: Dockerfile
    ports:
      - "6000:6000"

  promptify:
    container_name: promptify
    restart: always
    build:
      context: ./promptify
      dockerfile: Dockerfile
    ports:
      - "6000:6000"
  
  prompts:
    container_name: prompts
    restart: always
    build:
      context: ./prompts
      dockerfile: Dockerfile
    ports:
      - "7000:7000"